version: '3.8'
services:
  mongo-db-pt:
    ports:
      - '27018:27017'
    env_file: ./.env
    image: mongo:latest
    container_name: mongo-db-pt
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_DATABASE=${DOCKER_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DOCKER_DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASSWORD}
    expose:
      - '27018'
  app:
    container_name: app-container-pt
    image: app-container-pt
    depends_on:
      - mongo-db-pt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    volumes:
      - "./app:/usr/code/app"
      - "./app/index.ts:/usr/code/index.ts"
volumes:
  mongo-db-data:
